### PR TITLE
INTYGFV-15969: Added missing title text for question

### PR DESCRIPTION
**Pull request by mhornfeldt**

### CODE REVIEW

**Comment by mhornfeldt** [comment]
I feel like this question is missing the question text and that it has been "hacked" in the frontend in WC to add it. I don't think we should make another hack in MI. If we decide to go for this solution I will make sure that the WC frontend is updated.

**Review by ChrilleSigerhed — CHANGES_REQUESTED** [review]
Lets add an unit test to verify this change to the config!

**Comment by mhornfeldt** [comment]
> This question does not have its own title, therefore it should not have a text-attribute. I think we are better of not displaying the value at all if it has no value.

I'm not sure what you mean with not displaying the value but maybe this comment is outdated?

**Comment by ChrilleSigerhed** [comment]
> > This question does not have its own title, therefore it should not have a text-attribute. I think we are better of not displaying the value at all if it has no value.
> 
> I'm not sure what you mean with not displaying the value but maybe this comment is outdated?

**Review by ChrilleSigerhed — APPROVED** [review]
Nice, great that u solved this issue by adding text in config instead of trying to handle typeText!

**Pull request merged**
